services:
  db:
    image: postgres:15-alpine
    container_name: escenario_db
    environment:
      POSTGRES_DB: escenario_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superpassword123
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d